version: '3.8'

services:
  # 1. Your Custom .NET API Server
  ordersystem-api:
    image: ordersystem-api:latest
    build:
      context: . # Look in this folder
      dockerfile: OrderSystem.Api/Dockerfile
    ports:
      - "5055:8080"  # Expose port 5055 on your Windows Laptop, routing it to internal port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker # This triggers our custom appsettings overrides later!
    restart: always # If DB/RabbitMQ is slow to boot and API crashes, automatically revive it!
    depends_on:
      - sqlserver
      - redis
      - rabbitmq

  # 2. Redis Caching Engine
  redis:
    image: redis:latest
    restart: always
    # Notice there are no `ports` mapped. This database is purely internal to the Docker Network!
    # No hacker from the outside Internet can access it, only the API can.

  # 3. Microsoft SQL Server (Developer Edition)
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourSuper!Str0ngPassword!1
      - MSSQL_PID=Developer
    # Completely internally isolated from your laptop's normal SQL Server. Zero port conflicts!

  # 4. RabbitMQ Message Broker (With UI Dashboard)
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672" # The Management Website for you to physically view the queue!
    # Port 5672 is left unmapped. The API will talk to it internally over Docker.
