import { streamText } from 'ai';
import { createGoogleGenerativeAI } from '@ai-sdk/google';

const google = createGoogleGenerativeAI({
  apiKey: process.env.GEMINI_API_KEY,
});

export async function POST(req: Request) {
  // Gracefully parse the chat array generated by the frontend
  const { messages } = await req.json();

  // Initiate the physical connection to Google's neural network streaming engine
  const result = streamText({
    model: google('gemini-2.5-flash'),
    system: "You are the primary System AI for OrderSystem, a Fortune 500 microservice architecture running natively on Microsoft Azure. Act highly professional, concise, and helpful. You are providing support to users utilizing the dashboard.",
    messages,
  });

  // Stream back plain text chunks to the frontend fetch reader
  return result.toTextStreamResponse();
}
